language: python
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      dist: xenial
      env: TOXENV=py37
    - python: "pypy"
      env: TOXENV=pypy
    - python: "2.7"
      env: TOXENV=packaging
    - python: nightly  # Python 3.8.0a0
      dist: xenial     # required for Python 3.8-dev (travis-ci/travis-ci#9069)
  allow_failures:
    - python: nightly

install: "pip install -r requirements.txt"
script: "tox"

before_install:
  - pip install codecov coverage

after_success:
  - tox -e coverage-report
  - COVERAGE_FILE=.tox/.coverage coverage xml
  - codecov -f coverage.xml
