[tox]
envlist = py38,py39,py310,py311,pypy3
requires = tox-uv

[testenv]
changedir = .tox
dependency_groups = dev
commands =
    coverage run --rcfile {tox_root}/pyproject.toml --parallel -m pytest {posargs} {env_site_packages_dir}/clastic/tests/

[testenv:coverage-report]
changedir = .tox
dependency_groups = dev
commands =
    coverage combine --rcfile {tox_root}/pyproject.toml
    coverage xml --rcfile {tox_root}/pyproject.toml -o coverage.xml
    coverage report --rcfile {tox_root}/pyproject.toml
    coverage html --rcfile {tox_root}/pyproject.toml -d {tox_root}/htmlcov
